server:
  port: 8000

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sb_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 1
      min-idle: 1
      max-wait: 10
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 1
      max-open-prepared-statements: 1
      validation-query: SELECT 1
      validation-query-timeout: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
      time-between-connect-error-millis: 10
      min-evictable-idle-time-millis: 10
      max-evictable-idle-time-millis: 10
  quartz:
    job-store-type: jdbc #job类型
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler #调度器实例名称
            instanceId: AUTO #调度器实例编号自动生成
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化方式配置 RAMJobStore：基于内存存储job;JobStoreCMT：基于数据库的数据存储，并且受运行的java容器的事务控制;JobStoreTX：基于数据库的数据存储，不受事务控制
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #持久化方式配置数据驱动，MySQL数据库
            tablePrefix: QRTZ_ #quartz相关数据表前缀名
            isClustered: true #开启分布式部署
            clusterCheckinInterval: 10000 #分布式节点有效性检查时间间隔，单位：毫秒
            useProperties: false #配置是否使用
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool #线程池实现类
            threadCount: 10 #执行最大并发线程数量
            threadPriority: 5 #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true #配置是否启动自动加载数据库内的定时任务，默认true



mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.miao.spring.demo.domain, com.miao.spring.demo.domain.dto

