server:
  port: 8000

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 1
      min-idle: 1
      max-wait: 10
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 1
      max-open-prepared-statements: 1
      validation-query: SELECT 1
      validation-query-timeout: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
      time-between-connect-error-millis: 10
      min-evictable-idle-time-millis: 10
      max-evictable-idle-time-millis: 10
      filters: ...

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.miao.spring.demo.domain

